# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fb47e16e1bf5b05ac10541da07704f78f1be980c0aea6ccb66bd21c932f12d9c4fb0f18cfa7045de83817c270c990f55bf0c9718007ed9f8e8c3a5094df17ff

test:
  secret_key_base: 15864e0768c264bc7d8d6634c3370896a0ab0d3b32c563f6880452e8d203847c4179c5976b174120a6e103947dee331f87f287927cce567790ddf09a407e51e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
